name: predyktor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - sqlite
  - sqlalchemy
  - joblib
  - cython
  - numba
  - nltk
  - pip
  - pip:
    - -r backend/requirements.txt
    # dodatkowo przydatne narzędzia
    - python-dotenv
    - openai
