[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

# SPA routing fallback (also have _redirects in public/)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


