name: predyktor-polmaratonu
services:
- name: backend
  source_dir: /backend-deploy
  github:
    repo: JacaP30/predyktor_react
    branch: main
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: PORT
    value: "8080"
    scope: RUN_TIME
  http_port: 8080
  health_check:
    http_path: /
- name: frontend
  type: STATIC_SITE
  source_dir: /frontend
  github:
    repo: JacaP30/predyktor_react
    branch: main
  build_command: npm install && npm run build
  output_dir: build
  env:
  - key: REACT_APP_API_BASE
    value: "${backend.PUBLIC_URL}"
    scope: BUILD_TIME
